// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voting.Models.DbContexts;

namespace Voting.Migrations.Election
{
    [DbContext(typeof(ElectionDbContext))]
    [Migration("20190425155934_AddAlreadyVotedTable")]
    partial class AddAlreadyVotedTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Voting.Areas.Identity.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("StudentId");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Voting.Models.AlreadyVoted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentId");

                    b.Property<bool>("Voted");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("AlreadyVoted");
                });

            modelBuilder.Entity("Voting.Models.Candidate", b =>
                {
                    b.Property<int>("CanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CandidateName")
                        .HasMaxLength(20);

                    b.Property<int?>("CategoryCatId");

                    b.Property<string>("Photo");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("Year");

                    b.HasKey("CanId");

                    b.HasIndex("CategoryCatId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Voting.Models.Category", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(60);

                    b.Property<byte[]>("TimeSamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("CatId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Voting.Models.Votes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CandidateCanId");

                    b.Property<int?>("CategoryCatId");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("VoteCount");

                    b.HasKey("Id");

                    b.HasIndex("CandidateCanId");

                    b.HasIndex("CategoryCatId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Voting.Models.AlreadyVoted", b =>
                {
                    b.HasOne("Voting.Areas.Identity.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("Voting.Models.Candidate", b =>
                {
                    b.HasOne("Voting.Models.Category", "Category")
                        .WithMany("Candidates")
                        .HasForeignKey("CategoryCatId");
                });

            modelBuilder.Entity("Voting.Models.Votes", b =>
                {
                    b.HasOne("Voting.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateCanId");

                    b.HasOne("Voting.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCatId");
                });
#pragma warning restore 612, 618
        }
    }
}
